// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hr-system/internal/leaves/domain"

	mock "github.com/stretchr/testify/mock"
)

// LeaveService is an autogenerated mock type for the LeaveService type
type LeaveService struct {
	mock.Mock
}

// CreateLeave provides a mock function with given fields: ctx, leave
func (_m *LeaveService) CreateLeave(ctx context.Context, leave *domain.Leave) (domain.Leave, error) {
	ret := _m.Called(ctx, leave)

	if len(ret) == 0 {
		panic("no return value specified for CreateLeave")
	}

	var r0 domain.Leave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Leave) (domain.Leave, error)); ok {
		return rf(ctx, leave)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Leave) domain.Leave); ok {
		r0 = rf(ctx, leave)
	} else {
		r0 = ret.Get(0).(domain.Leave)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Leave) error); ok {
		r1 = rf(ctx, leave)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeaveByID provides a mock function with given fields: ctx, id
func (_m *LeaveService) GetLeaveByID(ctx context.Context, id int) (domain.Leave, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveByID")
	}

	var r0 domain.Leave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Leave, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Leave); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Leave)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeaves provides a mock function with given fields: ctx, query
func (_m *LeaveService) GetLeaves(ctx context.Context, query domain.LeavesQuery) ([]domain.Leave, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaves")
	}

	var r0 []domain.Leave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery) ([]domain.Leave, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery) []domain.Leave); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Leave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LeavesQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewLeave provides a mock function with given fields: ctx, leaveID, reviewerID, decision, comment
func (_m *LeaveService) ReviewLeave(ctx context.Context, leaveID int, reviewerID int, decision domain.ReviewStatus, comment string) error {
	ret := _m.Called(ctx, leaveID, reviewerID, decision, comment)

	if len(ret) == 0 {
		panic("no return value specified for ReviewLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.ReviewStatus, string) error); ok {
		r0 = rf(ctx, leaveID, reviewerID, decision, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaveService creates a new instance of LeaveService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveService {
	mock := &LeaveService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
