version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB_NAME=app_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REST_SERVER_PORT=8080
#    volumes:
#      - ..:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      retries: 10
      start_period: 1s
      timeout: 1s

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis-data:/data

volumes:
  mysql-data:
