// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hr-system/internal/leaves/domain"

	mock "github.com/stretchr/testify/mock"
)

// LeaveCache is an autogenerated mock type for the LeaveCache type
type LeaveCache struct {
	mock.Mock
}

// DelLeaveFromCache provides a mock function with given fields: ctx, id
func (_m *LeaveCache) DelLeaveFromCache(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DelLeaveFromCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelLeavesFromCache provides a mock function with given fields: ctx, query
func (_m *LeaveCache) DelLeavesFromCache(ctx context.Context, query domain.LeavesQuery) error {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for DelLeavesFromCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery) error); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLeaveFromCache provides a mock function with given fields: ctx, id
func (_m *LeaveCache) GetLeaveFromCache(ctx context.Context, id int) (domain.Leave, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveFromCache")
	}

	var r0 domain.Leave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Leave, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Leave); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Leave)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeavesFromCache provides a mock function with given fields: ctx, query
func (_m *LeaveCache) GetLeavesFromCache(ctx context.Context, query domain.LeavesQuery) ([]domain.Leave, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetLeavesFromCache")
	}

	var r0 []domain.Leave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery) ([]domain.Leave, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery) []domain.Leave); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Leave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LeavesQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLeaveToCache provides a mock function with given fields: ctx, leave
func (_m *LeaveCache) SetLeaveToCache(ctx context.Context, leave *domain.Leave) error {
	ret := _m.Called(ctx, leave)

	if len(ret) == 0 {
		panic("no return value specified for SetLeaveToCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Leave) error); ok {
		r0 = rf(ctx, leave)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLeavesToCache provides a mock function with given fields: ctx, query, leaves
func (_m *LeaveCache) SetLeavesToCache(ctx context.Context, query domain.LeavesQuery, leaves []domain.Leave) error {
	ret := _m.Called(ctx, query, leaves)

	if len(ret) == 0 {
		panic("no return value specified for SetLeavesToCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LeavesQuery, []domain.Leave) error); ok {
		r0 = rf(ctx, query, leaves)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaveCache creates a new instance of LeaveCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveCache {
	mock := &LeaveCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
